// <auto-generated />
using System;
using CourtPulse.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourtPulse.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CourtPulseDbContext))]
    [Migration("20260701213303_AddLiveGameState")]
    partial class AddLiveGameState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourtPulse.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentFirstPoints")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentSecondPoints")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EventTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("EventType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<long>("ExternalEventKey")
                        .HasColumnType("bigint");

                    b.Property<string>("FinalResult")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FirstPlayerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("MomentumFirstCumulative")
                        .HasColumnType("double precision");

                    b.Property<double>("MomentumFirstEwma")
                        .HasColumnType("double precision");

                    b.Property<double>("MomentumSecondCumulative")
                        .HasColumnType("double precision");

                    b.Property<double>("MomentumSecondEwma")
                        .HasColumnType("double precision");

                    b.Property<string>("Round")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("SecondPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Serving")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.HasIndex("ExternalEventKey")
                        .IsUnique();

                    b.HasIndex("FirstPlayerId");

                    b.HasIndex("IsLive");

                    b.HasIndex("SecondPlayerId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MomentumProcessed")
                        .HasColumnType("boolean");

                    b.Property<int>("PlayerServed")
                        .HasColumnType("integer");

                    b.Property<string>("Score")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ServeWinner")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "SetNumber", "GameNumber")
                        .IsUnique();

                    b.ToTable("MatchGames");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBreakPoint")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMatchPoint")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSetPoint")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchGameId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Score")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MatchGameId", "PointNumber")
                        .IsUnique();

                    b.ToTable("MatchPoints");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScoreFirst")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreSecond")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "SetNumber")
                        .IsUnique();

                    b.ToTable("MatchSets");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MomentumSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Beneficiary")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Delta")
                        .HasColumnType("double precision");

                    b.Property<double>("FirstCumulative")
                        .HasColumnType("double precision");

                    b.Property<double>("FirstEwma")
                        .HasColumnType("double precision");

                    b.Property<int>("GameNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PointNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("SecondCumulative")
                        .HasColumnType("double precision");

                    b.Property<double>("SecondEwma")
                        .HasColumnType("double precision");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "SetNumber", "GameNumber", "PointNumber");

                    b.ToTable("MomentumSnapshots");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalKey")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.PlayerMatchStatistic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("StatPeriod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("StatTotal")
                        .HasColumnType("integer");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("StatValue")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("StatWon")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "PlayerId", "StatType", "StatName")
                        .IsUnique();

                    b.ToTable("PlayerMatchStatistics");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExternalKey")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.Match", b =>
                {
                    b.HasOne("CourtPulse.Domain.Entities.Player", "FirstPlayer")
                        .WithMany()
                        .HasForeignKey("FirstPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtPulse.Domain.Entities.Player", "SecondPlayer")
                        .WithMany()
                        .HasForeignKey("SecondPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtPulse.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CourtPulse.Domain.Entities.Player", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FirstPlayer");

                    b.Navigation("SecondPlayer");

                    b.Navigation("Tournament");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchGame", b =>
                {
                    b.HasOne("CourtPulse.Domain.Entities.Match", null)
                        .WithMany("Games")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchPoint", b =>
                {
                    b.HasOne("CourtPulse.Domain.Entities.MatchGame", null)
                        .WithMany("Points")
                        .HasForeignKey("MatchGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchSet", b =>
                {
                    b.HasOne("CourtPulse.Domain.Entities.Match", null)
                        .WithMany("Sets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MomentumSnapshot", b =>
                {
                    b.HasOne("CourtPulse.Domain.Entities.Match", null)
                        .WithMany("MomentumSnapshots")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.PlayerMatchStatistic", b =>
                {
                    b.HasOne("CourtPulse.Domain.Entities.Match", null)
                        .WithMany("Statistics")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.Match", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("MomentumSnapshots");

                    b.Navigation("Sets");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.MatchGame", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("CourtPulse.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
